"""add order operations and refunds

Revision ID: 11afb608bbbe
Revises: 465f19371895
Create Date: 2026-08-30 14:40:30.158949
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "11afb608bbbe"
down_revision: str | None = "465f19371895"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

order_status = postgresql.ENUM(
    "AWAITING_PAYMENT",
    "CONFIRMED",
    "PROCESSING",
    "OUT_FOR_DELIVERY",
    "COMPLETED",
    "CANCELLED",
    "REFUND_REQUIRED",
    name="order_status",
    create_type=False,
)
refund_mode = postgresql.ENUM("MANUAL", name="refund_mode")
refund_status = postgresql.ENUM("PENDING", "SUCCESS", "FAILED", name="refund_status")


def upgrade() -> None:
    refund_mode.create(op.get_bind(), checkfirst=True)
    refund_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_status_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("previous_status", order_status, nullable=False),
        sa.Column("new_status", order_status, nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_order_status_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_events_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_events")),
        sa.UniqueConstraint("idempotency_key_hash", name="uq_order_status_events_idempotency_hash"),
    )
    op.create_index(
        "ix_order_status_events_order_created",
        "order_status_events",
        ["order_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "mode",
            postgresql.ENUM("MANUAL", name="refund_mode", create_type=False),
            server_default=sa.text("'MANUAL'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "SUCCESS", "FAILED", name="refund_status", create_type=False
            ),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("manual_reference", sa.String(length=120), nullable=True),
        sa.Column("completed_idempotency_key_hash", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("completed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_refunds_amount_positive")),
        sa.CheckConstraint("length(currency) = 3", name=op.f("ck_refunds_currency_length")),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["users.id"],
            name=op.f("fk_refunds_completed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_refunds_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_refunds_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_refunds_payment_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
        sa.UniqueConstraint(
            "completed_idempotency_key_hash", name="uq_refunds_completed_idempotency_hash"
        ),
        sa.UniqueConstraint("order_id", name="uq_refunds_order_id"),
    )
    op.create_index("ix_refunds_status_created", "refunds", ["status", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refunds_status_created", table_name="refunds")
    op.drop_table("refunds")
    op.drop_index("ix_order_status_events_order_created", table_name="order_status_events")
    op.drop_table("order_status_events")
    refund_status.drop(op.get_bind(), checkfirst=True)
    refund_mode.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
