"""create checkout orders and reservations

Revision ID: 26970b5634d2
Revises: b3e549cff94b
Create Date: 2026-08-29 16:45:34.985054
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "26970b5634d2"
down_revision: str | None = "b3e549cff94b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_areas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
        sa.Column("display_position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fee_minor >= 0", name=op.f("ck_delivery_areas_fee_non_negative")),
        sa.CheckConstraint("length(currency) = 3", name=op.f("ck_delivery_areas_currency_length")),
        sa.CheckConstraint(
            "length(name) BETWEEN 1 AND 120", name=op.f("ck_delivery_areas_name_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_areas")),
        sa.UniqueConstraint("name", name="uq_delivery_areas_name"),
    )
    op.create_index(
        "ix_delivery_areas_active_position",
        "delivery_areas",
        ["is_active", "display_position"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_number", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("customer_full_name", sa.String(length=120), nullable=False),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column("customer_email", sa.String(length=254), nullable=True),
        sa.Column("delivery_area_id", sa.UUID(), nullable=False),
        sa.Column("delivery_area_name", sa.String(length=120), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=False),
        sa.Column("delivery_directions", sa.Text(), nullable=True),
        sa.Column("subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column("delivery_fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
        sa.Column("attribution_source", sa.String(length=50), nullable=True),
        sa.Column("attribution_campaign", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AWAITING_PAYMENT",
                "CONFIRMED",
                "PROCESSING",
                "OUT_FOR_DELIVERY",
                "COMPLETED",
                "CANCELLED",
                "REFUND_REQUIRED",
                name="order_status",
            ),
            server_default=sa.text("'AWAITING_PAYMENT'"),
            nullable=False,
        ),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_fee_minor >= 0", name=op.f("ck_orders_delivery_fee_non_negative")
        ),
        sa.CheckConstraint("length(currency) = 3", name=op.f("ck_orders_currency_length")),
        sa.CheckConstraint("subtotal_minor >= 0", name=op.f("ck_orders_subtotal_non_negative")),
        sa.CheckConstraint(
            "total_minor = subtotal_minor + delivery_fee_minor",
            name=op.f("ck_orders_total_matches"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_area_id"],
            ["delivery_areas.id"],
            name=op.f("fk_orders_delivery_area_id_delivery_areas"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("access_token_hash", name=op.f("uq_orders_access_token_hash")),
        sa.UniqueConstraint("idempotency_key_hash", name="uq_orders_idempotency_key_hash"),
        sa.UniqueConstraint("order_number", name="uq_orders_order_number"),
    )
    op.create_index("ix_orders_status_created", "orders", ["status", "created_at"], unique=False)
    op.create_table(
        "inventory_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CONVERTED", "RELEASED", "EXPIRED", name="reservation_status"),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_inventory_reservations_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reservations")),
        sa.UniqueConstraint("order_id", name="uq_inventory_reservations_order_id"),
    )
    op.create_index(
        "ix_inventory_reservations_status_expiry",
        "inventory_reservations",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("internal_reference", sa.String(length=64), nullable=False),
        sa.Column("provider_reference", sa.String(length=128), nullable=True),
        sa.Column("payment_url", sa.Text(), nullable=True),
        sa.Column("expected_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "INITIALIZING",
                "PENDING",
                "SUCCESS",
                "FAILED",
                "PARTIALLY_REFUNDED",
                "REFUNDED",
                name="payment_status",
            ),
            server_default=sa.text("'INITIALIZING'"),
            nullable=False,
        ),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_amount_minor >= 0", name=op.f("ck_payments_amount_non_negative")
        ),
        sa.CheckConstraint("length(currency) = 3", name=op.f("ck_payments_currency_length")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("internal_reference", name="uq_payments_internal_reference"),
    )
    op.create_index(
        "ix_payments_status_created", "payments", ["status", "created_at"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=180), nullable=False),
        sa.Column("variant_name", sa.String(length=140), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("unit_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("line_subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_subtotal_minor = unit_price_minor * quantity",
            name=op.f("ck_order_items_subtotal_matches"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price_minor >= 0", name=op.f("ck_order_items_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_order_items_variant_id_product_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index("ix_order_items_order", "order_items", ["order_id"], unique=False)
    op.create_table(
        "reservation_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_reservation_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["inventory_reservations.id"],
            name=op.f("fk_reservation_items_reservation_id_inventory_reservations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_reservation_items_variant_id_product_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_items")),
        sa.UniqueConstraint("reservation_id", "variant_id", name="uq_reservation_items_variant"),
    )
    op.create_foreign_key(
        op.f("fk_inventory_movements_order_id_orders"),
        "inventory_movements",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_inventory_movements_reservation_id_inventory_reservations"),
        "inventory_movements",
        "inventory_reservations",
        ["reservation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_inventory_movements_reservation_id_inventory_reservations"),
        "inventory_movements",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_inventory_movements_order_id_orders"), "inventory_movements", type_="foreignkey"
    )
    op.drop_table("reservation_items")
    op.drop_index("ix_order_items_order", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_payments_status_created", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_inventory_reservations_status_expiry", table_name="inventory_reservations")
    op.drop_table("inventory_reservations")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_delivery_areas_active_position", table_name="delivery_areas")
    op.drop_table("delivery_areas")
    sa.Enum(name="payment_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="reservation_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
