"""record payment confirmation events

Revision ID: 465f19371895
Revises: 26970b5634d2
Create Date: 2026-08-29 17:30:06.521392
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "465f19371895"
down_revision: str | None = "26970b5634d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("event_key", sa.String(length=160), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("reported_status", sa.String(length=30), nullable=False),
        sa.Column("processing_result", sa.String(length=40), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_events_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
        sa.UniqueConstraint("provider", "event_key", name="uq_payment_events_provider_key"),
    )
    op.create_index(
        "ix_payment_events_payment_received",
        "payment_events",
        ["payment_id", "received_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payment_events_payment_received", table_name="payment_events")
    op.drop_table("payment_events")
    # ### end Alembic commands ###
