"""index order analytics window

Revision ID: 691cce0ae4b7
Revises: 11afb608bbbe
Create Date: 2026-08-30 15:24:08.896023
"""

from collections.abc import Sequence

from alembic import op

revision: str = "691cce0ae4b7"
down_revision: str | None = "11afb608bbbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_orders_created_at", "orders", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_created_at", table_name="orders")
    # ### end Alembic commands ###
