"""create catalogue core

Revision ID: 768649519f16
Revises:
Create Date: 2026-08-29 11:03:22.112929
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "768649519f16"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("display_position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(name) BETWEEN 1 AND 100", name=op.f("ck_categories_name_length")
        ),
        sa.CheckConstraint(
            "length(slug) BETWEEN 1 AND 120", name=op.f("ck_categories_slug_length")
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_categories_not_own_parent")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name="uq_categories_slug"),
    )
    op.create_index(
        "ix_categories_active_position",
        "categories",
        ["is_active", "display_position"],
        unique=False,
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("base_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("compare_at_price_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "ARCHIVED", name="product_status"),
            server_default=sa.text("'DRAFT'"),
            nullable=False,
        ),
        sa.Column("featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_price_minor >= 0", name=op.f("ck_products_base_price_non_negative")
        ),
        sa.CheckConstraint(
            "compare_at_price_minor IS NULL OR compare_at_price_minor > base_price_minor",
            name=op.f("ck_products_compare_at_price_above_price"),
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 180", name=op.f("ck_products_name_length")),
        sa.CheckConstraint("length(slug) BETWEEN 1 AND 200", name=op.f("ck_products_slug_length")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("slug", name="uq_products_slug"),
    )
    op.create_index(
        "ix_products_category_status", "products", ["category_id", "status"], unique=False
    )
    op.create_index(
        "ix_products_public_listing", "products", ["status", "featured", "created_at"], unique=False
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("cloudinary_public_id", sa.String(length=255), nullable=False),
        sa.Column("secure_url", sa.Text(), nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("height > 0", name=op.f("ck_product_images_height_positive")),
        sa.CheckConstraint("position >= 0", name=op.f("ck_product_images_position_non_negative")),
        sa.CheckConstraint("width > 0", name=op.f("ck_product_images_width_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
        sa.UniqueConstraint("cloudinary_public_id", name="uq_product_images_cloudinary_public_id"),
        sa.UniqueConstraint("product_id", "position", name="uq_product_images_product_position"),
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("colour", sa.String(length=80), nullable=True),
        sa.Column("size", sa.String(length=40), nullable=True),
        sa.Column("display_name", sa.String(length=140), nullable=False),
        sa.Column("price_override_minor", sa.BigInteger(), nullable=True),
        sa.Column("stock_on_hand", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), server_default=sa.text("2"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="variant_status"),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0",
            name=op.f("ck_product_variants_low_stock_threshold_non_negative"),
        ),
        sa.CheckConstraint(
            "price_override_minor IS NULL OR price_override_minor >= 0",
            name=op.f("ck_product_variants_price_override_non_negative"),
        ),
        sa.CheckConstraint(
            "reserved_quantity <= stock_on_hand",
            name=op.f("ck_product_variants_reserved_not_above_stock_on_hand"),
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0",
            name=op.f("ck_product_variants_reserved_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "stock_on_hand >= 0", name=op.f("ck_product_variants_stock_on_hand_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint("sku", name="uq_product_variants_sku"),
    )
    op.create_index(
        "ix_product_variants_product_status",
        "product_variants",
        ["product_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_product_variants_option_combination",
        "product_variants",
        [
            "product_id",
            sa.literal_column("coalesce(lower(colour), '')"),
            sa.literal_column("coalesce(lower(size), '')"),
        ],
        unique=True,
    )
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "INITIAL_STOCK",
                "ADMIN_ADJUSTMENT",
                "SALE",
                "CANCELLATION_RESTOCK",
                "RETURN_RESTOCK",
                name="inventory_movement_type",
            ),
            nullable=False,
        ),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(reason) BETWEEN 1 AND 500", name=op.f("ck_inventory_movements_reason_length")
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0", name=op.f("ck_inventory_movements_quantity_delta_non_zero")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_movements_variant_id_product_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
        sa.UniqueConstraint("idempotency_key", name="uq_inventory_movements_idempotency_key"),
    )
    op.create_index(
        "ix_inventory_movements_variant_created",
        "inventory_movements",
        ["variant_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inventory_movements_variant_created", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index("uq_product_variants_option_combination", table_name="product_variants")
    op.drop_index("ix_product_variants_product_status", table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_table("product_images")
    op.drop_index("ix_products_public_listing", table_name="products")
    op.drop_index("ix_products_category_status", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index("ix_categories_active_position", table_name="categories")
    op.drop_table("categories")
    sa.Enum(name="inventory_movement_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="variant_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="product_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
