"""create admin identity and sessions

Revision ID: b3e549cff94b
Revises: 768649519f16
Create Date: 2026-08-29 11:38:33.295489
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b3e549cff94b"
down_revision: str | None = "768649519f16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_login_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=False),
        sa.Column("network_hash", sa.String(length=64), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_login_attempts")),
    )
    op.create_index(
        "ix_admin_login_attempts_email_created",
        "admin_login_attempts",
        ["email_hash", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_admin_login_attempts_network_created",
        "admin_login_attempts",
        ["network_hash", "created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.Enum("OWNER", "ADMIN", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_normalized_email", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admin_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_admin_sessions_token_hash")),
    )
    op.create_index("ix_admin_sessions_expiry", "admin_sessions", ["expires_at"], unique=False)
    op.create_index(
        "ix_admin_sessions_user_expiry", "admin_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_inventory_movements_actor_user_id_users"),
        "inventory_movements",
        "users",
        ["actor_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_inventory_movements_actor_user_id_users"),
        "inventory_movements",
        type_="foreignkey",
    )
    op.drop_index("ix_admin_sessions_user_expiry", table_name="admin_sessions")
    op.drop_index("ix_admin_sessions_expiry", table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_index("uq_users_normalized_email", table_name="users")
    op.drop_table("users")
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
    op.drop_index("ix_admin_login_attempts_network_created", table_name="admin_login_attempts")
    op.drop_index("ix_admin_login_attempts_email_created", table_name="admin_login_attempts")
    op.drop_table("admin_login_attempts")
    # ### end Alembic commands ###
