"""create store settings singleton

Revision ID: c4a1e7f2b903
Revises: 691cce0ae4b7
Create Date: 2026-09-05 12:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c4a1e7f2b903"
down_revision: str | None = "691cce0ae4b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("singleton_guard", sa.Integer(), nullable=False),
        sa.Column("store_name", sa.String(length=120), nullable=False),
        sa.Column("logo_ref", sa.String(length=500), nullable=True),
        sa.Column("whatsapp_number", sa.String(length=20), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("instagram_url", sa.String(length=500), nullable=True),
        sa.Column("tiktok_url", sa.String(length=500), nullable=True),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("minimum_order_minor", sa.BigInteger(), nullable=True),
        sa.Column("business_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_idempotency_key_hash", sa.String(length=64), nullable=True),
        sa.Column("last_request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(currency) = 3", name=op.f("ck_store_settings_currency_length")),
        sa.CheckConstraint(
            "length(store_name) BETWEEN 2 AND 120", name=op.f("ck_store_settings_store_name_length")
        ),
        sa.CheckConstraint("singleton_guard = 1", name=op.f("ck_store_settings_singleton_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_settings")),
        sa.UniqueConstraint("singleton_guard", name="uq_store_settings_singleton_guard"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("store_settings")
    # ### end Alembic commands ###
