"""create analytics events

Revision ID: d7f3a2b9c1e4
Revises: c4a1e7f2b903
Create Date: 2026-09-06 12:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d7f3a2b9c1e4"
down_revision: str | None = "c4a1e7f2b903"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("campaign", sa.String(length=100), nullable=True),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('product_view', 'share_click', 'whatsapp_click')",
            name=op.f("ck_analytics_events_event_type_allowlist"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_analytics_events_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
    )
    op.create_index(
        "ix_analytics_events_product_created",
        "analytics_events",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_analytics_events_type_created",
        "analytics_events",
        ["event_type", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analytics_events_type_created", table_name="analytics_events")
    op.drop_index("ix_analytics_events_product_created", table_name="analytics_events")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
