from __future__ import annotations

import hashlib
import hmac
from collections.abc import Mapping
from urllib.parse import quote

import httpx

from bukkystore_api.config import Settings
from bukkystore_api.errors import ApiError


def require_cloudinary(settings: Settings) -> tuple[str, str, str]:
    if not (
        settings.cloudinary_cloud_name
        and settings.cloudinary_api_key
        and settings.cloudinary_api_secret
    ):
        raise ApiError(
            503,
            "image_service_unavailable",
            "Product photography has not been configured yet.",
        )
    return (
        settings.cloudinary_cloud_name,
        settings.cloudinary_api_key.get_secret_value(),
        settings.cloudinary_api_secret.get_secret_value(),
    )


def sign_parameters(parameters: Mapping[str, str | int], api_secret: str) -> str:
    serialized = "&".join(f"{key}={parameters[key]}" for key in sorted(parameters))
    return hashlib.sha256(f"{serialized}{api_secret}".encode()).hexdigest()


def verify_upload_response(
    *, public_id: str, version: int, signature: str, api_secret: str
) -> bool:
    serialized = f"public_id={public_id}&version={version}{api_secret}".encode()
    if len(signature) == 40:
        # Cloudinary response signatures default to SHA-1 even when the upload
        # request itself uses SHA-256. This verifies provider compatibility;
        # new authentication signatures generated by this API remain SHA-256.
        expected = hashlib.sha1(serialized, usedforsecurity=False).hexdigest()
    else:
        expected = hashlib.sha256(serialized).hexdigest()
    return hmac.compare_digest(expected, signature)


def delivery_url(*, cloud_name: str, public_id: str, version: int, image_format: str) -> str:
    safe_cloud = quote(cloud_name, safe="")
    safe_public_id = "/".join(quote(part, safe="") for part in public_id.split("/"))
    return (
        f"https://res.cloudinary.com/{safe_cloud}/image/upload/"
        f"v{version}/{safe_public_id}.{image_format}"
    )


async def destroy_image(public_id: str, settings: Settings, timestamp: int) -> None:
    cloud_name, api_key, api_secret = require_cloudinary(settings)
    parameters: dict[str, str | int] = {
        "invalidate": "true",
        "public_id": public_id,
        "timestamp": timestamp,
    }
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            response = await client.post(
                f"https://api.cloudinary.com/v1_1/{quote(cloud_name, safe='')}/image/destroy",
                data={
                    **parameters,
                    "api_key": api_key,
                    "signature": sign_parameters(parameters, api_secret),
                },
            )
            response.raise_for_status()
            result = response.json().get("result")
    except (httpx.HTTPError, ValueError, AttributeError) as exc:
        raise ApiError(
            502, "image_delete_failed", "The image provider could not remove this photo."
        ) from exc
    if result not in {"ok", "not found"}:
        raise ApiError(502, "image_delete_failed", "The image provider did not remove this photo.")
